model: claude:claude-sonnet-4-20250514
save_shell_history: true
editor: zeditor
clients:
  - type: claude
    api-key: $CLAUDE_API_KEY
  - type: openai
    api-key: $OPENAI_API_KEY
  - type: openai-compatible
    name: jina
    api-key: $JINA_API_KEY
    max_tokens_per_chunk: 8192
    default_chunk_size: 7800
    max_batch_size: 100

# --- RAG ---
rag_embedding_model: text-embedding-ada-002

# ---- session ----
# Controls the persistence of the session. if true, auto save; if false, not save; if null, asking the user
save_session: false
# Compress session when token count reaches or exceeds this threshold
compress_threshold: 40000
